// CarTracker 
Blockly.Msg.WEBDUINO_CARTRACKER_SET = "設定";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT_FRONT = "馬達腳位 右前";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT_BACK = "右後"
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT_FRORT = "左前";
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT_BACK = "左後";
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT = "感測器腳位  L";
Blockly.Msg.WEBDUINO_CARTRACKER_CENTER = " C";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT = " R";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT_MOTOR = "右輪";
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT_MOTOR = "左輪";
Blockly.Msg.WEBDUINO_CARTRACKER_BOTH_MOTOR = "兩輪";
Blockly.Msg.WEBDUINO_CARTRACKER_SPEED = "速度";
Blockly.Msg.WEBDUINO_CARTRACKER_PERCENT = "％";
Blockly.Msg.WEBDUINO_CARTRACKER_WHEN = "當";
Blockly.Msg.WEBDUINO_CARTRACKER_INDUCTION = "循跡偵測訊號為";
Blockly.Msg.WEBDUINO_CARTRACKER_MOTION = "時，動作";
Blockly.Msg.WEBDUINO_CARTRACKER_DO = "運行";
Blockly.Msg.WEBDUINO_CARTRACKER_ON = "啟動循跡";
Blockly.Msg.WEBDUINO_CARTRACKER_OFF = "停止循跡";
Blockly.Msg.WEBDUINO_CARTRACKER_STOP = "停止";
Blockly.Msg.WEBDUINO_CARTRACKER_FORWARD = "前進";
Blockly.Msg.WEBDUINO_CARTRACKER_TURN_LEFT = "原地左轉";
Blockly.Msg.WEBDUINO_CARTRACKER_TURN_RIGHT = "原地右轉";
Blockly.Msg.WEBDUINO_CARTRACKER_BACK = "後退";
Blockly.Msg.WEBDUINO_CARTRACKER_TURN_LEFT_SLOWLY= "原地慢速左轉";
Blockly.Msg.WEBDUINO_CARTRACKER_TURN_RIGHT_SLOWLY = "原地慢速右轉";
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT_FORWARD = "左前";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT_FORWARD = "右前";
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT_BACK = "左後";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT_BACK = "右後";




